<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDWSAjad\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDWSAjad/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerDWSAjad.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerDWSAjad\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerDWSAjad\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'DWSAjad',
    'container.build_id' => '3ff20e55',
    'container.build_time' => 1771156649,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDWSAjad');
